// Per-run real private key material for unit tests (Task 1, 02-06-PLAN.md). Every key is
// generated by shelling out to the host's own `ssh-keygen`/`openssl` into a directory created
// with `mkdtemp` under the OS temp dir — never inside the repository tree, and never committed.
// This module is excluded from the production build (`tsconfig.build.json`'s `src/testing/**`
// exclusion, declared in plan 02-01) and from coverage (`vitest.config.ts`), and
// `packages/ssh/src/index.ts` must never export it: it exists solely for
// `key-loader.test.ts`/`fingerprint.test.ts` to exercise real key parsing without ever writing a
// literal PEM private-key header string into a source file.
import { execFileSync } from 'node:child_process';
import { generateKeyPairSync, randomBytes } from 'node:crypto';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

export interface TestKeySet {
  readonly ed25519: string;
  readonly ecdsa: string;
  readonly rsa3072: string;
  readonly rsa1024: string;
  readonly rsa3072Pem: string;
  readonly ed25519Locked: string;
  readonly ed25519LockedPassphrase: string;
  /**
   * A DSA key, traditional OpenSSL PEM form (the classic `-----BEGIN DSA ...-----` single-block
   * header). Not named in this plan's own `<action>` key list, but required by
   * key-loader.test.ts's D-01 "rejects a DSA key... naming the accepted types" assertion — the
   * loader must be exercised against a key `utils.parseKey` genuinely parses
   * (`.type === 'ssh-dss'`) and then rejects on type, not a generic parse failure. Modern
   * `ssh-keygen` (measured on this host) refuses `-t dsa` outright ("unknown key type dsa" —
   * OpenSSH deprecated and removed DSA key *generation*, though `ssh2`'s parser still reads the
   * legacy format), so `openssl dsaparam`/`gendsa` produces it instead — both are already-required
   * host tools in this project's engineering environment.
   */
  readonly dsa: string;
  /** Idempotent: safe to call more than once. Removes the temporary directory recursively. */
  cleanup(): void;
}

function keygen(dir: string, name: string, args: readonly string[], passphrase = ''): void {
  execFileSync(
    'ssh-keygen',
    ['-q', '-N', passphrase, '-f', join(dir, name), ...args],
    { stdio: 'ignore' },
  );
}

/**
 * `ssh-keygen -b 1024` for RSA is measured to still work on this project's dev host (OpenSSH
 * 10.2), but some distributions' OpenSSH builds refuse a modulus below their own configured
 * minimum. Falls back to `node:crypto`'s own RSA generator (PKCS#1 PEM, the same format
 * `ssh-keygen -m PEM` produces) so the below-2048-bit rejection path this key exists to exercise
 * never depends on the host's `ssh-keygen` accepting a legacy key size.
 */
function generateRsa1024(dir: string, name: string): void {
  try {
    keygen(dir, name, ['-t', 'rsa', '-b', '1024']);
    return;
  } catch {
    // fall through to the node:crypto fallback below
  }
  const { privateKey } = generateKeyPairSync('rsa', {
    modulusLength: 1024,
    publicKeyEncoding: { type: 'spki', format: 'pem' },
    privateKeyEncoding: { type: 'pkcs1', format: 'pem' },
  });
  writeFileSync(join(dir, name), privateKey, { mode: 0o600 });
}

/**
 * Legacy OpenSSL DSA generation (see `TestKeySet.dsa`'s doc comment for why `ssh-keygen` cannot
 * produce this). Two-step (`dsaparam` then `gendsa`) rather than `dsaparam -genkey`, whose output
 * file also contains a leading `-----BEGIN DSA PARAMETERS-----` block that `ssh2`'s anchored
 * (`^...$`) traditional-PEM regex would reject.
 */
function generateDsa(dir: string): void {
  const paramsPath = join(dir, 'dsaparam.pem');
  execFileSync('openssl', ['dsaparam', '-out', paramsPath, '1024'], { stdio: 'ignore' });
  execFileSync('openssl', ['gendsa', '-out', join(dir, 'dsa'), paramsPath], { stdio: 'ignore' });
}

export function generateTestKeys(): TestKeySet {
  const dir = mkdtempSync(join(tmpdir(), 'noodara-ssh-test-keys-'));

  const ed25519LockedPassphrase = randomBytes(18).toString('base64url');

  keygen(dir, 'ed25519', ['-t', 'ed25519']);
  keygen(dir, 'ecdsa', ['-t', 'ecdsa', '-b', '256']);
  keygen(dir, 'rsa3072', ['-t', 'rsa', '-b', '3072']);
  keygen(dir, 'rsa3072_pem', ['-t', 'rsa', '-b', '3072', '-m', 'PEM']);
  keygen(dir, 'ed25519_locked', ['-t', 'ed25519'], ed25519LockedPassphrase);
  generateRsa1024(dir, 'rsa1024');
  generateDsa(dir);

  const read = (name: string): string => readFileSync(join(dir, name), 'utf8');

  let cleaned = false;
  const cleanup = (): void => {
    if (cleaned) return;
    cleaned = true;
    rmSync(dir, { recursive: true, force: true });
  };

  return {
    ed25519: read('ed25519'),
    ecdsa: read('ecdsa'),
    rsa3072: read('rsa3072'),
    rsa1024: read('rsa1024'),
    rsa3072Pem: read('rsa3072_pem'),
    ed25519Locked: read('ed25519_locked'),
    ed25519LockedPassphrase,
    dsa: read('dsa'),
    cleanup,
  };
}
