// The brand board (07-04-PLAN.md Task 1, D-12/D-14) as a pure string builder.
//
// One board per concept per theme is what the user reads in 07-05 alongside the in-app captures.
// D-14 fixes its contents: the three lockups, a construction sheet on the real 24-unit grid, the
// 16/32/64/256 scale ladder and the favicon tile -- plus, from D-12, a preview of the Open Graph
// image. Pitfall 2 of 07-RESEARCH.md fixes what the board may NOT claim: Playwright cannot
// screenshot the browser's own tab strip, so the tile is shown on a SIMULATED bar that says so in
// words, and the real tab stays a manual check.
//
// THIS MODULE DRAWS NOTHING. Every mark on the board is `renderStaticSvg`/`tileSvg` output from
// 07-03 -- a render of the very components apps/web mounts -- so a board can never show a mark the
// app does not have. There is no geometry here: no coordinate, no radius, no angle. The only
// shapes this file assembles itself are the construction sheet's grid lines and guides, which are
// annotations over the mark rather than part of it.
//
// COLOUR. The board is the design system rendering itself: `tokensCss` is inlined verbatim and
// every surface, ink and hairline is a `var(--token)` reference. Exactly four literal colours may
// appear in the markup, and all four are the caller's: the tile's `background`/`ink` (D-11 -- the
// favicon is the one blue surface) and the OG image's `canvas`/`ink` (D-12 -- light ink on the
// dark canvas, regardless of which theme the board itself is in). The lockups are rendered with
// the literal string `currentColor`, which `static-svg.ts` deliberately does not contain, so the
// board's own `color: var(--ink)` is what paints them.
//
// The simulated tab strips need BOTH theme palettes on one page, whatever theme the board is in.
// `tokens.css` only carries a `[data-theme="dark"]` block (light lives under `:root`, which
// matches the document element only), so this module re-emits that same `:root` body -- taken from
// the passed `tokensCss`, never retyped -- as a `[data-theme="light"]` block. That is why both
// strips can sit side by side on a dark board and still be honest about their own palettes.
//
// NO SCRIPT, NO NETWORK, NO EMOJI (docs/ui-build-prompt.md section 9). The board is inert markup
// rendered by `page.setContent` with no navigation: no `<script>`, no event handler attribute, no
// `href`/`src`, no `url(` (so no web font and no remote image), no gradient, no shadow.

import {
  APERTURE_RADIUS,
  BASELINE,
  CONCEPT_META,
  GRID,
  MARGIN,
  STROKE,
  fmt,
  lockupLayout,
  monogramParts,
  wordmarkWidth,
  type ConceptId,
} from '../../packages/ui/src/brand/geometry.js';
import { renderStaticSvg, tileSvg } from '../../packages/ui/src/brand/static-svg.js';
import type { Theme } from './review-paths.js';

/** The review sizes D-14 names: a favicon, a rail icon, a card icon and a presentation size. */
export const BOARD_SCALES = [16, 32, 64, 256] as const;

/** `--r-md` (10px) on a 44px control -- the ratio `tileSvg` uses to keep an icon's corner inside
 *  the system's own radius family at every size (see static-svg.ts). */
const TILE_RADIUS_RATIO = 10 / 44;

/** The ink the board's own lockups inherit. `static-svg.ts` holds no colour literal at all, not
 *  even this one, precisely so the caller decides -- and on the board the caller wants the CSS
 *  cascade, i.e. `color: var(--ink)` on the body. */
const INHERIT = 'currentColor';

const TAGLINE = 'Your infrastructure, understood.';
const TAB_DISCLAIMER = 'Simulated browser tab — verify the real tab manually';
const FOOTER_NOTE = 'Generated by pnpm brand:boards — do not edit';

const CONSTRUCTION_SIZE = 480;

export interface BoardOptions {
  readonly concept: ConceptId;
  readonly theme: Theme;
  /** `packages/ui/tokens.css`, read from disk by the caller and inlined verbatim. */
  readonly tokensCss: string;
  /** D-11: the favicon tile's two colours (`--accent-fill` on `--on-accent`). */
  readonly tile: { readonly background: string; readonly ink: string };
  /** D-12: the OG image's two colours (the dark `--canvas` and the dark `--ink`). */
  readonly og: { readonly canvas: string; readonly ink: string };
}

// --- Rendering helpers -------------------------------------------------------------------------

/** `renderStaticSvg` renders at the components' own default size (the 24-unit grid), because the
 *  static export path has no size argument by design. The board needs the same mark at eight
 *  different sizes, so this rewrites the root element's `width`/`height` -- and only those, since
 *  nothing else in the rendered markup carries either attribute. The `viewBox` is untouched, so
 *  the result is the identical drawing at a different scale. */
const ROOT_SIZE_RE = / width="[\d.]+" height="[\d.]+"/;

function sized(svg: string, width: number, height: number): string {
  return svg.replace(ROOT_SIZE_RE, ` width="${fmt(width)}" height="${fmt(height)}"`);
}

function monogramSvg(concept: ConceptId, size: number, color: string): string {
  return sized(renderStaticSvg({ kind: 'monogram', concept, color }), size, size).trimEnd();
}

function lockupSvg(concept: ConceptId, height: number, color: string): string {
  const layout = lockupLayout(concept);
  const width = Math.round((height * layout.width) / layout.height);
  return sized(renderStaticSvg({ kind: 'lockup', concept, color }), width, height).trimEnd();
}

function wordmarkSvg(concept: ConceptId, height: number, color: string): string {
  const width = Math.round((height * wordmarkWidth(concept)) / GRID);
  return sized(renderStaticSvg({ kind: 'wordmark', concept, color }), width, height).trimEnd();
}

function tile(concept: ConceptId, size: number, options: BoardOptions): string {
  return tileSvg({
    concept,
    background: options.tile.background,
    ink: options.tile.ink,
    size,
    radiusRatio: TILE_RADIUS_RATIO,
  }).replace(/\n/g, '');
}

// --- Style -------------------------------------------------------------------------------------

/** Re-emits the `:root` declarations from the passed tokens CSS under `[data-theme="light"]`, so
 *  an element inside a dark board can opt into the light palette (the simulated light tab strip).
 *  The values are the file's own, lifted verbatim -- this module never states a token value. */
const ROOT_BLOCK_RE = /:root\s*\{([\s\S]*?)\}/;

function lightThemeBlock(tokensCss: string): string {
  const match = ROOT_BLOCK_RE.exec(tokensCss);
  if (match === null || match[1] === undefined) {
    // Fail loud: a silent fallback would render the "light" tab strip in dark tokens and quietly
    // misinform the very review this board exists for.
    throw new Error('board-html.ts: the tokens CSS carried no :root block to derive a light theme from');
  }
  return `[data-theme="light"] {${match[1]}}`;
}

const BOARD_CSS = `
  *, *::before, *::after { box-sizing: border-box; }
  body {
    margin: 0;
    background: var(--canvas);
    color: var(--ink);
    font-family: var(--font-sans);
    font-size: var(--text-body-size);
    line-height: var(--text-body-line-height);
    letter-spacing: var(--text-body-tracking);
    -webkit-font-smoothing: antialiased;
  }
  .board { width: 1200px; margin: 0 auto; padding: var(--space-12) var(--space-8); }
  section, header, footer { padding: var(--space-8) 0; border-top: 1px solid var(--hairline); }
  header { border-top: 0; padding-top: 0; }
  h1 {
    margin: 0 0 var(--space-2);
    font-family: var(--text-display-font);
    font-size: var(--text-display-size);
    line-height: var(--text-display-line-height);
    letter-spacing: var(--text-display-tracking);
    font-weight: var(--text-display-weight);
  }
  h2 {
    margin: 0 0 var(--space-5);
    font-family: var(--text-title-font);
    font-size: var(--text-title-size);
    line-height: var(--text-title-line-height);
    letter-spacing: var(--text-title-tracking);
    font-weight: var(--text-title-weight);
  }
  p { margin: 0; }
  .lead { color: var(--ink-secondary); max-width: 68ch; }
  .caption {
    font-size: var(--text-caption-size);
    line-height: var(--text-caption-line-height);
    color: var(--ink-tertiary);
  }
  .row { display: flex; align-items: flex-end; gap: var(--space-12); flex-wrap: wrap; }
  figure { margin: 0; display: flex; flex-direction: column; gap: var(--space-3); }
  .swatch {
    display: flex;
    align-items: center;
    justify-content: center;
    background: var(--surface-1);
    border: 1px solid var(--hairline);
    border-radius: var(--r-md);
    padding: var(--space-4);
  }
  .mono {
    font-family: var(--font-mono);
    font-size: var(--text-mono-size);
    line-height: var(--text-mono-line-height);
  }
  .list { display: flex; flex-direction: column; gap: var(--space-1); margin: 0 0 var(--space-6); }
  .construction { position: relative; width: ${String(CONSTRUCTION_SIZE)}px; height: ${String(CONSTRUCTION_SIZE)}px; }
  .construction > * { position: absolute; inset: 0; }
  .strip {
    display: flex;
    align-items: center;
    gap: var(--space-2);
    width: 320px;
    height: 40px;
    padding: 0 var(--space-3);
    background: var(--surface-2);
    color: var(--ink);
    border: 1px solid var(--hairline);
    border-bottom: 0;
    border-radius: var(--r-sm) var(--r-sm) 0 0;
  }
  .strip span { font-size: var(--text-caption-size); }
  .og-frame { width: 600px; height: 315px; overflow: hidden; border: 1px solid var(--hairline); border-radius: var(--r-md); }
  .og-inner {
    width: 1200px;
    height: 630px;
    transform: scale(0.5);
    transform-origin: top left;
    display: flex;
    flex-direction: column;
    justify-content: center;
    gap: 56px;
    padding: 0 120px;
  }
  .og-tagline { font-family: var(--text-display-font); font-size: 56px; letter-spacing: -0.02em; font-weight: 600; }
`;

// --- Sections ----------------------------------------------------------------------------------

function header(options: BoardOptions): string {
  const meta = CONCEPT_META[options.concept];
  return [
    '<header>',
    `<p class="caption mono">Concept ${meta.id.toUpperCase()} &middot; ${options.theme}</p>`,
    `<h1>${meta.name}</h1>`,
    `<p class="lead">${meta.meaning}</p>`,
    '</header>',
  ].join('');
}

function lockupsSection(options: BoardOptions): string {
  const { concept } = options;
  return [
    '<section data-board-section="lockups">',
    '<h2>Lockups</h2>',
    '<div class="row">',
    `<figure data-board-lockup="monogram"><div class="swatch">${monogramSvg(concept, 96, INHERIT)}</div><figcaption class="caption">Monogram</figcaption></figure>`,
    `<figure data-board-lockup="lockup"><div class="swatch">${lockupSvg(concept, 48, INHERIT)}</div><figcaption class="caption">Horizontal lockup</figcaption></figure>`,
    `<figure data-board-lockup="wordmark"><div class="swatch">${wordmarkSvg(concept, 48, INHERIT)}</div><figcaption class="caption">Wordmark</figcaption></figure>`,
    '</div>',
    '</section>',
  ].join('');
}

/** The 24x24 grid, the margin box and the baseline the mark is built on, as annotation lines under
 *  the real monogram. Straight lines and one rectangle only -- this is a ruler, not a drawing. */
function gridSvg(): string {
  const lines: string[] = [];
  for (let i = 0; i <= GRID; i += 1) {
    const at = fmt(i);
    lines.push(`<line x1="${at}" y1="0" x2="${at}" y2="${fmt(GRID)}" stroke="var(--hairline-strong)" stroke-width="0.04"/>`);
    lines.push(`<line x1="0" y1="${at}" x2="${fmt(GRID)}" y2="${at}" stroke="var(--hairline-strong)" stroke-width="0.04"/>`);
  }
  const inner = fmt(GRID - 2 * MARGIN);
  lines.push(
    `<rect x="${fmt(MARGIN)}" y="${fmt(MARGIN)}" width="${inner}" height="${inner}" fill="none" stroke="var(--ink-secondary)" stroke-width="0.08"/>`,
  );
  lines.push(
    `<line x1="0" y1="${fmt(BASELINE)}" x2="${fmt(GRID)}" y2="${fmt(BASELINE)}" stroke="var(--ink-secondary)" stroke-width="0.08"/>`,
  );
  return [
    `<svg xmlns="http://www.w3.org/2000/svg" data-grid="${String(GRID)}" viewBox="0 0 ${fmt(GRID)} ${fmt(GRID)}"`,
    ` width="${String(CONSTRUCTION_SIZE)}" height="${String(CONSTRUCTION_SIZE)}" aria-hidden="true">`,
    lines.join(''),
    '</svg>',
  ].join('');
}

/** Every constant the mark is derived from, read from `geometry.ts` -- a D-16 adjustment round
 *  retunes the module and this sheet follows on the next `pnpm brand:boards`. */
const CONSTANTS: readonly (readonly [string, number])[] = [
  ['GRID', GRID],
  ['MARGIN', MARGIN],
  ['STROKE', STROKE],
  ['APERTURE_RADIUS', APERTURE_RADIUS],
  ['BASELINE', BASELINE],
];

function constructionSection(options: BoardOptions): string {
  const { concept } = options;
  const constants = CONSTANTS.map(([name, value]) => `<p class="mono">${name} = ${fmt(value)}</p>`).join('');
  const parts = monogramParts(concept)
    .map((part) => `<p class="mono">${part.part}</p>`)
    .join('');
  return [
    '<section data-board-section="construction">',
    '<h2>Construction</h2>',
    '<div class="row">',
    `<div class="construction">${gridSvg()}${monogramSvg(concept, CONSTRUCTION_SIZE, INHERIT)}</div>`,
    '<div>',
    '<p class="caption">Constants (geometry.ts)</p>',
    `<div class="list">${constants}</div>`,
    '<p class="caption">Parts, in DOM order</p>',
    `<div class="list">${parts}</div>`,
    '</div>',
    '</div>',
    '</section>',
  ].join('');
}

function scalesSection(options: BoardOptions): string {
  const items = BOARD_SCALES.map(
    (scale) =>
      `<figure data-board-scale="${String(scale)}"><div class="swatch">${monogramSvg(options.concept, scale, INHERIT)}</div><figcaption class="caption mono">${String(scale)} px</figcaption></figure>`,
  ).join('');
  return [
    '<section data-board-section="scales">',
    '<h2>Scales</h2>',
    `<div class="row">${items}</div>`,
    '</section>',
  ].join('');
}

function strip(theme: Theme, options: BoardOptions): string {
  return [
    `<figure data-strip="${theme}" data-theme="${theme}">`,
    '<div class="strip">',
    tile(options.concept, 16, options),
    '<span>Noodara</span>',
    tile(options.concept, 32, options),
    '</div>',
    `<figcaption class="caption">${TAB_DISCLAIMER}</figcaption>`,
    '</figure>',
  ].join('');
}

function tabStripsSection(options: BoardOptions): string {
  return [
    '<section data-board-section="tab-strips">',
    '<h2>Favicon tile</h2>',
    `<div class="row">${strip('light', options)}${strip('dark', options)}</div>`,
    '</section>',
  ].join('');
}

function ogSection(options: BoardOptions): string {
  const { og, concept } = options;
  return [
    '<section data-board-section="og-preview">',
    '<h2>Open Graph image</h2>',
    '<div data-board-og="1200x630" class="og-frame">',
    `<div class="og-inner" style="background: ${og.canvas}; color: ${og.ink};">`,
    lockupSvg(concept, 120, og.ink),
    `<p class="og-tagline">${TAGLINE}</p>`,
    '</div>',
    '</div>',
    `<p class="caption">1200 &times; 630, shown at half size.</p>`,
    '</section>',
  ].join('');
}

// --- Document ----------------------------------------------------------------------------------

/** Builds one complete, self-contained brand board. Pure: same options in, same bytes out. */
export function buildBoardHtml(options: BoardOptions): string {
  const meta = CONCEPT_META[options.concept];
  return [
    '<!doctype html>',
    `<html lang="en" data-theme="${options.theme}">`,
    '<head>',
    '<meta charset="utf-8">',
    `<title>Noodara brand board &mdash; concept ${meta.id.toUpperCase()} (${options.theme})</title>`,
    '<style>',
    options.tokensCss,
    lightThemeBlock(options.tokensCss),
    BOARD_CSS,
    '</style>',
    '</head>',
    '<body>',
    '<div class="board">',
    header(options),
    lockupsSection(options),
    constructionSection(options),
    scalesSection(options),
    tabStripsSection(options),
    ogSection(options),
    `<footer><p class="caption">${FOOTER_NOTE}</p></footer>`,
    '</div>',
    '</body>',
    '</html>',
    '',
  ].join('\n');
}
