// Where a brand-review artifact lives on disk (07-04-PLAN.md Task 1, D-14/BRAND-03).
//
// Two scripts write into this tree -- `render-boards.ts` (the static brand board per concept and
// theme) and `capture-brand-review.ts` (the same concepts mounted in the real app) -- and the
// approval plan (07-05) reads it back to copy the chosen concept's captures into
// `docs/brand/approved/`. All three agree because they call this module, never because they each
// spell the same string correctly.
//
// PATHS COME FROM THE MODULE'S OWN LOCATION, NEVER FROM THE PROCESS'S WORKING DIRECTORY.
// `pnpm brand:review` must write the same files whether it is invoked from the repo root, from
// `scripts/`, or by a future CI step started somewhere else entirely -- the same discipline
// `write-if-changed.ts` (07-02) already applies to its own repo-root resolution. (The forbidden
// API is named descriptively rather than literally so the gate that greps for it stays exact,
// following 07-03's own precedent in `packages/ui/src/index.ts`.)
//
// EVERYTHING UNDER THE REVIEW ROOT IS GITIGNORED EXCEPT `README.md` (see `.gitignore`'s "Brand
// review captures" block). These are throwaway artifacts of a review round, regenerated by one
// command; only the concept the user approves is ever committed, and that is 07-05's job.

import path from 'node:path';
import type { ConceptId } from '../../packages/ui/src/brand/geometry.js';

/** `scripts/brand/` -> repo root, matching `write-if-changed.ts`'s own resolution. */
const REPO_ROOT = path.resolve(import.meta.dirname, '../..');

/** The directory every board and capture is written under. */
export const REVIEW_ROOT = path.join(REPO_ROOT, 'docs', 'brand', 'review');

/** The four in-app surfaces D-14 requires the user to see the mark on, in the order
 *  `capture-brand-review.ts` visits them (the two unauthenticated screens are captured first, on a
 *  fresh browser context with empty fields -- T-07-09 -- so no credential is ever on screen). */
export const REVIEW_SURFACES = ['sidebar-expanded', 'sidebar-rail', 'login', 'setup'] as const;
export type ReviewSurface = (typeof REVIEW_SURFACES)[number];

export const THEMES = ['light', 'dark'] as const;
export type Theme = (typeof THEMES)[number];

/** A capture's absolute path. `surface` is one of the four in-app surfaces or the literal
 *  `'board'` (the static brand board, which has no app surface of its own); `variant` marks a
 *  tighter second shot of the same surface -- the cropped sidebar -- so it sorts next to its own
 *  full-page capture in a file listing. */
export function reviewPngPath(
  concept: ConceptId,
  surface: ReviewSurface | 'board',
  theme: Theme,
  variant?: 'crop',
): string {
  const suffix = variant === undefined ? '' : `-${variant}`;
  return path.join(REVIEW_ROOT, concept, `${surface}-${theme}${suffix}.png`);
}
