// 06-07-PLAN.md Task 2: stands the real production `docker-compose.yml` up for real -- six
// services built from the real Dockerfiles (06-03/06-05), driven as a real `docker compose` child
// process (never Testcontainers: this suite proves the Compose *file* itself, exactly as an
// operator's `docker compose up -d` would run it, not container orchestration in the abstract).
//
// `.env` is generated by calling install.sh's own real `noodara_generate_env` (06-04, hardened by
// the post-06-04 security fix) through `runInstallerShell` -- never hand-written -- so the Compose
// file and the installer's env writer can never silently drift apart from each other.
//
// Hygiene (hard_rule #7): every container/network/volume this suite creates is namespaced under a
// single random project name (`PROJECT_NAME`), the web port is a random free port bound to
// 127.0.0.1 only, and `afterAll` tears the whole project down with `down --volumes
// --remove-orphans` before asserting nothing of that project name remains. This suite does not add
// a `noodara.test=true` label to any container: that convention belongs to
// GenericContainer/Testcontainers-driven suites (control-plane-image.test.ts, web-image.test.ts);
// adding a test-only label to the *production* docker-compose.yml purely so this suite could reuse
// `assertNoStrayTestContainers()` would be a worse compromise than scoping the stray-check by this
// run's own project name instead. `assertNoStrayTestContainers()` is still called at the very end
// as a defence-in-depth check against unrelated leakage, but it is not this suite's primary
// cleanup proof.
import { execFileSync, spawnSync } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import { cpSync, mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { createServer } from 'node:net';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { runInstallerShell } from '../../unit/installer/sh-harness.js';
import { assertNoStrayTestContainers } from '../helpers/ssh.js';

const HERE = path.dirname(fileURLToPath(import.meta.url));
// Resolved from this file's own location, never process.cwd() (mirrors control-plane-image.test.ts
// and web-image.test.ts's own REPO_ROOT resolution).
const REPO_ROOT = path.resolve(HERE, '../../..');
const COMPOSE_PATH = path.join(REPO_ROOT, 'docker-compose.yml');
const CONTROL_PLANE_DOCKERFILE = 'apps/control-plane/Dockerfile';
const WEB_DOCKERFILE = 'apps/web/Dockerfile';

// Lowercase-only (Docker repository-name components must be lowercase) and namespaced with a
// random suffix so a concurrent or leftover-from-a-failed-run project can never collide with this
// one, the developer's own noodara-dev-* stack, or a real installation.
const RUN_ID = randomBytes(4).toString('hex');
const IMAGE_PREFIX = `noodara-test-0607-${RUN_ID}`;
const VERSION = `test-0607-${RUN_ID}`;
const PROJECT_NAME = `noodara-test-0607-${RUN_ID}`;
// A second, independent project used only by the admin-password-passthrough proof below --
// deliberately contains PROJECT_NAME as a substring, so afterAll's own `--filter name=` stray
// checks (both container and volume) also catch anything this second project might leave behind,
// on top of that test's own inline try/finally teardown.
const ADMIN_PROOF_PROJECT_NAME = `${PROJECT_NAME}-admin`;
const CONTROL_PLANE_IMAGE = `${IMAGE_PREFIX}/noodara-control-plane:${VERSION}`;
const WEB_IMAGE = `${IMAGE_PREFIX}/noodara-web:${VERSION}`;

const BUILD_TIMEOUT_MS = 600_000;
const UP_TIMEOUT_MS = 240_000;
const CLI_TIMEOUT_MS = 30_000;
const WAIT_TIMEOUT_SECONDS = 180;

/** POSIX single-quote escaping for embedding an arbitrary value into a shell snippet (mirrors
 *  tests/integration/installer/env-compose-roundtrip.test.ts's own shQuote). */
function shQuote(value: string): string {
  return `'${value.replace(/'/g, "'\\''")}'`;
}

/** Narrows a `describe`-scoped fixture variable assigned in `beforeAll` for use inside a sibling
 *  `it()` closure (mirrors web-image.test.ts's own local assertDefined helper). */
function assertDefined<T>(value: T | undefined, what: string): T {
  if (value === undefined) {
    throw new Error(`${what} is undefined -- beforeAll must have failed or not run yet`);
  }
  return value;
}

/** An OS-assigned free port on the loopback interface only -- hard_rule #7: the test's own
 *  published web port must never be reachable from the LAN, unlike the real production
 *  `${NOODARA_PORT}:3000` mapping (which intentionally binds every interface). */
function getFreePort(): Promise<number> {
  return new Promise((resolve, reject) => {
    const server = createServer();
    server.on('error', reject);
    server.listen(0, '127.0.0.1', () => {
      const address = server.address();
      if (address === null || typeof address === 'string') {
        reject(new Error('getFreePort: unexpected server address shape'));
        return;
      }
      const { port } = address;
      server.close(() => {
        resolve(port);
      });
    });
  });
}

interface ComposePsEntry {
  ID: string;
  Service: string;
  State: string;
  ExitCode: number;
  Health: string;
  Publishers: { PublishedPort: number }[];
}

function composePs(projectDir: string): ComposePsEntry[] {
  const out = execFileSync('docker', ['compose', '-p', PROJECT_NAME, 'ps', '-a', '--format', 'json'], {
    cwd: projectDir,
    encoding: 'utf8',
    timeout: CLI_TIMEOUT_MS,
  });
  return out
    .trim()
    .split('\n')
    .filter((line) => line.length > 0)
    .map((line) => JSON.parse(line) as ComposePsEntry);
}

interface ComposeConfigService {
  deploy?: { resources?: { limits?: { memory?: string } } };
}

interface ComposeConfigJson {
  services: Record<string, ComposeConfigService>;
}

/** The Compose file's OWN resolution of `deploy.resources.limits.memory`, in raw bytes --
 *  deliberately not a hand-rolled YAML parse (Assumption A3 must be replaced by a real
 *  measurement compared against Compose's own model, not by a second, possibly-drifting
 *  reimplementation of Compose's own interpolation/resolution rules). */
function composeConfig(projectDir: string): ComposeConfigJson {
  const out = execFileSync('docker', ['compose', '-p', PROJECT_NAME, 'config', '--format', 'json'], {
    cwd: projectDir,
    encoding: 'utf8',
    timeout: CLI_TIMEOUT_MS,
  });
  return JSON.parse(out) as ComposeConfigJson;
}

const MEMORY_UNIT_MULTIPLIERS: Record<string, number> = {
  B: 1,
  KIB: 1024,
  MIB: 1024 ** 2,
  GIB: 1024 ** 3,
  TIB: 1024 ** 4,
};

/** Parses one side of `docker stats`'s `MemUsage` field (e.g. `"38.07MiB"`) into raw bytes. */
function parseDockerMemoryToBytes(value: string): number {
  const match = /^([\d.]+)\s*([A-Za-z]+)$/.exec(value.trim());
  if (match === null) {
    throw new Error(`parseDockerMemoryToBytes: cannot parse "${value}"`);
  }
  const amountRaw = match[1];
  const unitRaw = match[2];
  if (amountRaw === undefined || unitRaw === undefined) {
    throw new Error(`parseDockerMemoryToBytes: regex match missing a capture group for "${value}"`);
  }
  const multiplier = MEMORY_UNIT_MULTIPLIERS[unitRaw.toUpperCase()];
  if (multiplier === undefined) {
    throw new Error(`parseDockerMemoryToBytes: unknown unit "${unitRaw}" in "${value}"`);
  }
  return Number(amountRaw) * multiplier;
}

/** A single, real `docker stats --no-stream` sample for one running container, in raw bytes. */
function measuredBytesFor(containerName: string): number {
  const raw = execFileSync('docker', ['stats', '--no-stream', '--format', '{{json .}}', containerName], {
    encoding: 'utf8',
    timeout: CLI_TIMEOUT_MS,
  }).trim();
  const stat = JSON.parse(raw) as { MemUsage: string };
  const used = stat.MemUsage.split('/')[0];
  if (used === undefined) {
    throw new Error(`measuredBytesFor: cannot parse MemUsage "${stat.MemUsage}"`);
  }
  return parseDockerMemoryToBytes(used);
}

/** Runs `docker compose ... up -d --wait` and throws with the full stdout/stderr on a non-zero
 *  exit -- `--wait` makes Compose itself block until every service reaches running|healthy (and a
 *  one-shot like `migrate` reaches its own terminal exited state), so a hung dependency surfaces
 *  as this function throwing within `WAIT_TIMEOUT_SECONDS`, never as a silent partial stack. */
function composeUp(projectDir: string): void {
  const result = spawnSync(
    'docker',
    ['compose', '-p', PROJECT_NAME, 'up', '-d', '--wait', '--wait-timeout', String(WAIT_TIMEOUT_SECONDS)],
    { cwd: projectDir, encoding: 'utf8', timeout: UP_TIMEOUT_MS },
  );
  if (result.status !== 0) {
    throw new Error(`docker compose up failed (status ${String(result.status)}):\n${result.stdout}\n${result.stderr}`);
  }
}

function composeLogs(projectDir: string, service: string): string {
  return execFileSync('docker', ['compose', '-p', PROJECT_NAME, 'logs', '--no-color', service], {
    cwd: projectDir,
    encoding: 'utf8',
    timeout: CLI_TIMEOUT_MS,
  });
}

function volumeExists(volumeName: string): string {
  return execFileSync('docker', ['volume', 'ls', '-q', '--filter', `name=${volumeName}`], {
    encoding: 'utf8',
    timeout: CLI_TIMEOUT_MS,
  }).trim();
}

describe('production docker-compose.yml stack (06-07-PLAN.md)', () => {
  let projectDir: string | undefined;
  let composeYaml: string | undefined;
  let webPort: number | undefined;

  beforeAll(async () => {
    // Reading the real file first: while Task 1 has not yet created docker-compose.yml, this
    // throws ENOENT and the whole suite fails for that exact reason -- the RED state hard_rule #5
    // requires this test to prove before docker-compose.yml exists at all.
    composeYaml = readFileSync(COMPOSE_PATH, 'utf8');

    execFileSync('docker', ['build', '--file', CONTROL_PLANE_DOCKERFILE, '--tag', CONTROL_PLANE_IMAGE, '.'], {
      cwd: REPO_ROOT,
      encoding: 'utf8',
      timeout: BUILD_TIMEOUT_MS,
    });
    execFileSync(
      'docker',
      [
        'build',
        '--file',
        WEB_DOCKERFILE,
        '--build-arg',
        'NOODARA_API_ORIGIN=http://api:3000',
        '--tag',
        WEB_IMAGE,
        '.',
      ],
      { cwd: REPO_ROOT, encoding: 'utf8', timeout: BUILD_TIMEOUT_MS },
    );

    // docker-compose.yml and .env are siblings in the project directory -- mirrors D-10's real
    // /opt/noodara layout, so `env_file: [.env]`'s relative path resolves exactly as it will on a
    // real install.
    projectDir = mkdtempSync(path.join(tmpdir(), 'noodara-compose-stack-'));
    cpSync(COMPOSE_PATH, path.join(projectDir, 'docker-compose.yml'));

    webPort = await getFreePort();

    // Generated by install.sh's own real function, never hand-written -- NOODARA_PORT is passed
    // as `127.0.0.1:<port>` so Compose's `${NOODARA_PORT}:3000` mapping resolves to a
    // loopback-only publish for this test run (hard_rule #7), while the production file's own
    // literal `${NOODARA_PORT}:3000` shape is completely unmodified: a real install's operator
    // supplies a bare port number and gets every interface published, exactly as intended.
    const genResult = runInstallerShell(
      '/bin/sh',
      [
        'noodara_generate_env',
        shQuote(path.join(projectDir, '.env')),
        shQuote(`http://localhost:${String(webPort)}`),
        shQuote(`127.0.0.1:${String(webPort)}`),
        shQuote(VERSION),
        shQuote(IMAGE_PREFIX),
      ].join(' '),
    );
    if (genResult.status !== 0) {
      throw new Error(`noodara_generate_env failed (status ${String(genResult.status)}): ${genResult.stderr}`);
    }
  }, BUILD_TIMEOUT_MS);

  afterAll(async () => {
    if (projectDir !== undefined) {
      spawnSync('docker', ['compose', '-p', PROJECT_NAME, 'down', '--volumes', '--remove-orphans'], {
        cwd: projectDir,
        timeout: UP_TIMEOUT_MS,
      });
      rmSync(projectDir, { recursive: true, force: true });
    }
    spawnSync('docker', ['rmi', '-f', CONTROL_PLANE_IMAGE], { stdio: 'ignore' });
    spawnSync('docker', ['rmi', '-f', WEB_IMAGE], { stdio: 'ignore' });

    // The primary cleanup proof (hard_rule #7): nothing bearing this run's own project name
    // remains, container or volume.
    expect(
      execFileSync('docker', ['ps', '-aq', '--filter', `name=${PROJECT_NAME}`], { encoding: 'utf8' }).trim(),
    ).toBe('');
    expect(
      execFileSync('docker', ['volume', 'ls', '-q', '--filter', `name=${PROJECT_NAME}`], { encoding: 'utf8' }).trim(),
    ).toBe('');

    // Defence in depth: this suite never labels a container `noodara.test=true` itself (see the
    // file header), so this call should always be a trivial pass here -- it only catches an
    // unrelated leak from a different suite that ran earlier in the same process.
    await assertNoStrayTestContainers();
  }, UP_TIMEOUT_MS);

  it(
    'brings up the real six-service stack, gates on migrate, proves redis health, publishes only web, survives a second up, and stays within measured memory limits',
    async () => {
      const dir = assertDefined(projectDir, 'projectDir');
      const yaml = assertDefined(composeYaml, 'composeYaml');

      // Structural shape (D-04/D-10/Pitfall 2), read directly from the file this beforeAll loaded
      // -- cheap, fast sanity checks alongside the real container-level proofs below.
      expect(yaml).not.toContain(':latest');
      expect((yaml.match(/^\s{4}ports:/gm) ?? []).length).toBe(1);
      expect(yaml).toContain('service_completed_successfully');
      expect(yaml).toMatch(/restart:\s*"no"/);

      composeUp(dir);

      const servicesAfterFirstUp = composePs(dir);
      const byService = new Map(servicesAfterFirstUp.map((entry) => [entry.Service, entry]));

      for (const name of ['postgres', 'redis', 'api', 'web']) {
        const entry = byService.get(name);
        if (entry === undefined) {
          throw new Error(`no "docker compose ps" entry for service "${name}"`);
        }
        expect(entry.Health, `${name} health`).toBe('healthy');
      }
      const migrateEntry = byService.get('migrate');
      if (migrateEntry === undefined) {
        throw new Error('no "docker compose ps" entry for service "migrate"');
      }
      expect(migrateEntry.State).toBe('exited');
      expect(migrateEntry.ExitCode).toBe(0);

      // T-06-33: redis reports healthy only because Task 1's container-side `REDIS_PASSWORD`
      // environment fix makes the authenticated healthcheck actually execute -- inspected
      // directly via `docker inspect`, not inferred from "the container is running".
      const redisHealth = execFileSync(
        'docker',
        ['inspect', `--format={{.State.Health.Status}}`, `${PROJECT_NAME}-redis-1`],
        { encoding: 'utf8', timeout: CLI_TIMEOUT_MS },
      ).trim();
      expect(redisHealth).toBe('healthy');

      // T-06-08: only `web` publishes a host port -- postgres/redis/api/worker/migrate must not,
      // even though api/worker legitimately EXPOSE 3000 in their own Dockerfile (an unpublished
      // "Ports" entry, distinct from an actual host-bound Publisher).
      for (const entry of servicesAfterFirstUp) {
        const publishedPorts = entry.Publishers.filter((publisher) => publisher.PublishedPort !== 0);
        if (entry.Service === 'web') {
          expect(publishedPorts.length, 'web should publish exactly one host port').toBe(1);
        } else {
          expect(publishedPorts, `${entry.Service} must not publish any host port`).toHaveLength(0);
        }
      }

      // The installer (Plan 06-09) reads this exact line from the api container's own logs.
      const apiLogs = composeLogs(dir, 'api');
      expect(apiLogs).toMatch(/NOODARA_SETUP_TOKEN=\S+/);

      const postgresVolumeName = `${PROJECT_NAME}_noodara_postgres_data`;
      const redisVolumeName = `${PROJECT_NAME}_noodara_redis_data`;
      const postgresVolumeBeforeSecondUp = volumeExists(postgresVolumeName);
      expect(postgresVolumeBeforeSecondUp).not.toBe('');
      expect(volumeExists(redisVolumeName)).not.toBe('');

      // A second `up -d` re-runs the one-shot `migrate` in place (docker/compose#9260, Pitfall
      // 2) -- confirmed empirically (same container ID, `up -d` simply restarts it) before writing
      // this assertion. Safe here only because Drizzle's migrate() is idempotent. `docker compose
      // logs` accumulates output from both runs for a service Compose restarts rather than
      // recreates, so the LAST "N migration(s) applied" match is this second run's own result.
      composeUp(dir);

      const migrateLogsAfterSecondUp = composeLogs(dir, 'migrate');
      const appliedMatches = [...migrateLogsAfterSecondUp.matchAll(/(\d+) migration\(s\) applied/g)];
      const lastApplied = appliedMatches.at(-1);
      if (lastApplied === undefined) {
        throw new Error(`expected "N migration(s) applied" in migrate logs, got:\n${migrateLogsAfterSecondUp}`);
      }
      const lastAppliedCount = lastApplied[1];
      if (lastAppliedCount === undefined) {
        throw new Error('regex match missing capture group 1');
      }
      expect(Number(lastAppliedCount)).toBe(0);

      const servicesAfterSecondUp = composePs(dir);
      const byServiceAfterSecondUp = new Map(servicesAfterSecondUp.map((entry) => [entry.Service, entry]));
      for (const name of ['postgres', 'redis', 'api', 'web']) {
        expect(byServiceAfterSecondUp.get(name)?.Health, `${name} health after second up`).toBe('healthy');
      }
      expect(byServiceAfterSecondUp.get('migrate')?.ExitCode).toBe(0);

      // "Nothing recreated unexpectedly": every long-running service keeps its own container ID
      // across the second `up` -- an unconfigured second `up` must not tear down and recreate a
      // container just because it re-ran. `migrate` is deliberately excluded: as a one-shot with
      // `restart: "no"`, Compose starts the SAME container again in place rather than recreating
      // it (confirmed empirically before writing this suite; docker/compose#9260), so its ID is
      // also expected to be unchanged -- included here too for completeness.
      for (const name of ['postgres', 'redis', 'migrate', 'api', 'worker', 'web']) {
        expect(byServiceAfterSecondUp.get(name)?.ID, `${name} container ID must not change on a second up`).toBe(
          byService.get(name)?.ID,
        );
      }

      // Data survives: same volume, still present, not recreated.
      expect(volumeExists(postgresVolumeName)).toBe(postgresVolumeBeforeSecondUp);

      // Memory: a real `docker stats --no-stream` sample taken while the stack is healthy,
      // compared against docker-compose.yml's own resolved `deploy.resources.limits.memory` (via
      // `docker compose config`, never a hand-parsed YAML read) -- Assumption A3 replaced by a
      // real measurement. `migrate` is deliberately excluded: by the time the stack is healthy it
      // has already exited (0B measured), so a 2x-of-zero comparison would be vacuous -- its own
      // limit is a documented, non-measured bound by analogy to api/worker's own measured
      // footprint from the identical base image (see docker-compose.yml's own comment and the
      // SUMMARY).
      const config = composeConfig(dir);
      const measuredBytesByService: Record<string, number> = {};
      for (const serviceName of ['postgres', 'redis', 'api', 'worker', 'web']) {
        const containerName = `${PROJECT_NAME}-${serviceName}-1`;
        const measuredBytes = measuredBytesFor(containerName);
        measuredBytesByService[serviceName] = measuredBytes;
        const limitRaw = config.services[serviceName]?.deploy?.resources?.limits?.memory;
        if (limitRaw === undefined) {
          throw new Error(`docker-compose.yml has no deploy.resources.limits.memory for "${serviceName}"`);
        }
        const limitBytes = Number(limitRaw);
        expect(limitBytes, `${serviceName} memory limit (${String(limitBytes)}B) vs 2x measured (${String(measuredBytes * 2)}B)`).toBeGreaterThanOrEqual(
          measuredBytes * 2,
        );
      }
      const migrateLimitRaw = config.services.migrate?.deploy?.resources?.limits?.memory;
      if (migrateLimitRaw === undefined) {
        throw new Error('docker-compose.yml has no deploy.resources.limits.memory for "migrate"');
      }
      expect(Number(migrateLimitRaw)).toBeGreaterThan(0);

      // Printed deliberately: the exact figures used to set docker-compose.yml's memory limits
      // belong in the SUMMARY verbatim (hard_rule requires the literal `docker stats --no-stream`
      // output), not reconstructed after the fact.
      console.log('measured memory (bytes, docker stats --no-stream):', JSON.stringify(measuredBytesByService));
    },
    600_000,
  );

  it(
    'a tricky admin password written by the real noodara_generate_env reaches the api container byte-for-byte',
    () => {
      // A synthetic fixture value ONLY -- never a real secret. Exercises exactly the character
      // classes install.sh's Finding B fix (06-04-SUMMARY.md "Post-execution security fix") had to
      // handle: '$', a space, ' #' (Compose's own inline-comment marker) and a double quote.
      const trickyPassword = 'p@ss$word #1 "q"';
      const adminEmail = 'admin@example.com';

      // This admin-proof stack is independent of the main test above (own project, own .env, own
      // temp dir) because setting NOODARA_ADMIN_EMAIL/PASSWORD makes bootstrap-admin pre-seed the
      // admin and skip emitting NOODARA_SETUP_TOKEN entirely (fase 1 D-04) -- the two behaviors
      // (setup-token proof vs. admin-password proof) are mutually exclusive within one `.env`.
      const projectDirForAdminProof = mkdtempSync(path.join(tmpdir(), 'noodara-compose-stack-admin-'));
      try {
        cpSync(COMPOSE_PATH, path.join(projectDirForAdminProof, 'docker-compose.yml'));

        const genResult = runInstallerShell(
          '/bin/sh',
          [
            'noodara_generate_env',
            shQuote(path.join(projectDirForAdminProof, '.env')),
            shQuote('http://localhost:65535'),
            shQuote('127.0.0.1:65535'),
            shQuote(VERSION),
            shQuote(IMAGE_PREFIX),
          ].join(' '),
          { env: { NOODARA_ADMIN_EMAIL: adminEmail, NOODARA_ADMIN_PASSWORD: trickyPassword } },
        );
        if (genResult.status !== 0) {
          throw new Error(`noodara_generate_env failed (status ${String(genResult.status)}): ${genResult.stderr}`);
        }

        try {
          // `up api` alone (no `worker`/`web` targets) still transitively brings up its real
          // dependencies (`migrate`, which itself depends on `postgres`, and `redis`) -- exactly
          // the subset this proof needs, without paying for the web image's own startup.
          const up = spawnSync(
            'docker',
            [
              'compose',
              '-p',
              ADMIN_PROOF_PROJECT_NAME,
              'up',
              '-d',
              '--wait',
              '--wait-timeout',
              String(WAIT_TIMEOUT_SECONDS),
              'api',
            ],
            { cwd: projectDirForAdminProof, encoding: 'utf8', timeout: UP_TIMEOUT_MS },
          );
          if (up.status !== 0) {
            throw new Error(`docker compose up (admin proof) failed (status ${String(up.status)}):\n${up.stdout}\n${up.stderr}`);
          }

          // The real proof: reads the value out of the CONTAINER's own process environment (never
          // .env, never `docker compose config`'s own re-serialization) through a real `docker
          // compose exec`, exactly as hard_rule requires.
          const readPassword = execFileSync(
            'docker',
            [
              'compose',
              '-p',
              ADMIN_PROOF_PROJECT_NAME,
              'exec',
              '-T',
              'api',
              'node',
              '-e',
              'process.stdout.write(process.env.NOODARA_ADMIN_PASSWORD ?? "")',
            ],
            { cwd: projectDirForAdminProof, encoding: 'utf8', timeout: CLI_TIMEOUT_MS },
          );
          expect(readPassword).toBe(trickyPassword);

          const readEmail = execFileSync(
            'docker',
            [
              'compose',
              '-p',
              ADMIN_PROOF_PROJECT_NAME,
              'exec',
              '-T',
              'api',
              'node',
              '-e',
              'process.stdout.write(process.env.NOODARA_ADMIN_EMAIL ?? "")',
            ],
            { cwd: projectDirForAdminProof, encoding: 'utf8', timeout: CLI_TIMEOUT_MS },
          );
          expect(readEmail).toBe(adminEmail);
        } finally {
          spawnSync('docker', ['compose', '-p', ADMIN_PROOF_PROJECT_NAME, 'down', '--volumes', '--remove-orphans'], {
            cwd: projectDirForAdminProof,
            timeout: UP_TIMEOUT_MS,
          });
        }
      } finally {
        rmSync(projectDirForAdminProof, { recursive: true, force: true });
      }
    },
    300_000,
  );
});
