// 06-04-PLAN.md Task 1: proves a generated `.env` is genuinely acceptable to the real, already-
// shipped apps/control-plane/src/env.ts fail-fast validator -- not a re-implementation of its
// rules in TypeScript. Variables are generated by calling install.sh's own real functions through
// runInstallerShell (never re-implemented here), then fed to a fresh `node` process that only
// imports the compiled dist/env.js -- importing env.ts directly would execute
// `loadEnv(process.env)` at module scope and call `process.exit(1)` on failure, which would kill
// the test runner itself. dist/env.js exists because vitest.installer.config.ts's globalSetup
// builds the workspace before this suite runs.
import { spawnSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { describe, expect, it } from 'vitest';
import { runInstallerShell } from '../../unit/installer/sh-harness.js';

const HERE = path.dirname(fileURLToPath(import.meta.url));
// Resolved from this file's own location, never process.cwd() -- mirrors
// control-plane-image.test.ts's REPO_ROOT resolution.
const REPO_ROOT = path.resolve(HERE, '../../..');
const ENV_JS_URL = pathToFileURL(path.resolve(REPO_ROOT, 'apps/control-plane/dist/env.js')).href;

interface GeneratedSecrets {
  masterKey: string;
  authSecret: string;
  databaseUrl: string;
  redisUrl: string;
}

/** Generates a full, real set of installer secrets by calling install.sh's own functions through
 *  runInstallerShell -- never re-implemented in TypeScript (this task's own <action> text). */
function generateSecrets(): GeneratedSecrets {
  const snippet = [
    'master_key=$(noodara_generate_secret base64)',
    'auth_secret=$(noodara_generate_secret hex)',
    'pg_password=$(noodara_generate_secret hex)',
    'redis_password=$(noodara_generate_secret hex)',
    'database_url=$(noodara_build_database_url "$pg_password")',
    'redis_url=$(noodara_build_redis_url "$redis_password")',
    'printf "MASTER_KEY=%s\\n" "$master_key"',
    'printf "AUTH_SECRET=%s\\n" "$auth_secret"',
    'printf "DATABASE_URL=%s\\n" "$database_url"',
    'printf "REDIS_URL=%s\\n" "$redis_url"',
  ].join('\n');

  const result = runInstallerShell('/bin/sh', snippet);
  if (result.status !== 0) {
    throw new Error(`install.sh secret generation failed with status ${String(result.status)}`);
  }

  const values: Record<string, string> = {};
  for (const line of result.stdout.trim().split('\n')) {
    const eq = line.indexOf('=');
    values[line.slice(0, eq)] = line.slice(eq + 1);
  }

  return {
    masterKey: values.MASTER_KEY ?? '',
    authSecret: values.AUTH_SECRET ?? '',
    databaseUrl: values.DATABASE_URL ?? '',
    redisUrl: values.REDIS_URL ?? '',
  };
}

/** Spawns a fresh node process that only imports the compiled env.js module. Its own top-level
 *  `export const env = loadEnv(process.env)` either completes silently (accepted, exit 0) or
 *  writes one `NOODARA_CONFIG_ERROR <VAR>: ...` line per issue to stderr and calls
 *  `process.exit(1)` (rejected). */
function loadCompiledEnv(vars: Record<string, string>): { status: number | null; stderr: string } {
  const result = spawnSync(
    process.execPath,
    ['--input-type=module', '-e', `await import(${JSON.stringify(ENV_JS_URL)});`],
    {
      encoding: 'utf8',
      env: { PATH: process.env.PATH ?? '', ...vars },
    },
  );
  return { status: result.status, stderr: result.stderr };
}

describe('a generated .env is accepted by the real compiled env.js validator', () => {
  it('a full generated variable set loads with exit 0 and no NOODARA_CONFIG_ERROR', () => {
    const secrets = generateSecrets();

    const { status, stderr } = loadCompiledEnv({
      NOODARA_MASTER_KEY: secrets.masterKey,
      BETTER_AUTH_SECRET: secrets.authSecret,
      DATABASE_URL: secrets.databaseUrl,
      REDIS_URL: secrets.redisUrl,
      NOODARA_PUBLIC_URL: 'http://203.0.113.10:3000',
      PORT: '3000',
    });

    expect(status).toBe(0);
    expect(stderr).not.toContain('NOODARA_CONFIG_ERROR');
  });

  // Negative control (this task's own regression target, 06-04-PLAN.md <context>): a base64
  // secret's '/', '+' or '=' characters corrupt DATABASE_URL/REDIS_URL when new URL() parses
  // them -- proving why every secret embedded in a URL must be hex, never base64. new URL() may
  // throw outright or silently mis-parse depending on where the '/' lands, so the assertion is on
  // the stronger, deterministic property directly: the round-tripped password never equals the
  // original secret.
  it('a base64 password containing "/" does not round-trip through URL parsing', () => {
    let base64WithSlash: string | undefined;
    for (let attempt = 0; attempt < 200 && base64WithSlash === undefined; attempt += 1) {
      const result = runInstallerShell('/bin/sh', 'noodara_generate_secret base64');
      const candidate = result.stdout.trim();
      if (candidate.includes('/')) {
        base64WithSlash = candidate;
      }
    }
    if (base64WithSlash === undefined) {
      throw new Error('could not find a base64 secret containing "/" after 200 attempts');
    }

    const databaseUrl = `postgresql://noodara:${base64WithSlash}@postgres:5432/noodara`;
    let roundTripped: string | undefined;
    try {
      roundTripped = decodeURIComponent(new URL(databaseUrl).password);
    } catch {
      roundTripped = undefined;
    }

    expect(roundTripped).not.toBe(base64WithSlash);
  });
});
