// Where a UI-review artifact lives on disk (08-01-PLAN.md Task 1, D-12/D-15).
//
// One script writes into this tree -- `capture-ui-review.ts` -- and the phase's gate plans
// (08-02/08-11/08-19, D-13) read it back to copy the approved 1280px captures into
// `docs/ui/approved/`. Both agree because they call this module, never because they each spell the
// same string correctly. Mirrors `scripts/brand/review-paths.ts`'s own shape (Phase 7 precedent).
//
// PATHS COME FROM THE MODULE'S OWN LOCATION, NEVER FROM THE PROCESS'S WORKING DIRECTORY.
// `pnpm ui:review` must write the same files whether it is invoked from the repo root, from
// `scripts/`, or by a future CI step started somewhere else entirely -- the same discipline
// `write-if-changed.ts` already applies to its own repo-root resolution. (The forbidden API is
// named descriptively rather than literally so the gate that greps for it stays exact, following
// `scripts/brand/review-paths.ts`'s own precedent.)
//
// EVERYTHING UNDER THE REVIEW ROOT IS GITIGNORED EXCEPT `README.md` (see `.gitignore`'s "UI review
// captures" block). These are throwaway artifacts of a review round, regenerated by one command;
// only the 1280px set the user approves is ever committed, under `docs/ui/approved/`, and that is
// each gate plan's own job (D-15).

import path from 'node:path';

/** `scripts/ui/` -> repo root, matching `scripts/brand/review-paths.ts`'s own resolution. */
const REPO_ROOT = path.resolve(import.meta.dirname, '../..');

/** The directory every review-round capture is written under (all widths, both themes). */
export const REVIEW_ROOT = path.join(REPO_ROOT, 'docs', 'ui', 'review');

/** The directory the approved 1280px-only set is committed under (D-15). */
export const APPROVED_ROOT = path.join(REPO_ROOT, 'docs', 'ui', 'approved');

/** The six redesigned screens (08-UI-SPEC.md §11.1), in the order `capture-ui-review.ts` visits
 *  them: the two unauthenticated screens first, on a fresh browser context with every field empty
 *  (T-08-02), then the four screens behind sign-in. */
export const SCREENS = ['setup', 'login', 'servers', 'server-detail', 'activity', 'settings'] as const;
export type Screen = (typeof SCREENS)[number];

/** The four overlay surfaces D-12 also requires, captured at 1280px only, both themes. */
export const OVERLAYS = ['sheet-open', 'dialog-open', 'row-menu-open', 'account-menu-open'] as const;
export type Overlay = (typeof OVERLAYS)[number];

export const THEMES = ['light', 'dark'] as const;
export type Theme = (typeof THEMES)[number];

export const WIDTHS = [375, 900, 1280, 1920] as const;
export type Width = (typeof WIDTHS)[number];

/** A review-round capture's absolute path -- one file per surface (screen or overlay), theme and
 *  width, regenerated on every `pnpm ui:review` run. */
export function reviewPngPath(surface: Screen | Overlay, theme: Theme, width: Width): string {
  return path.join(REVIEW_ROOT, `${surface}-${theme}-${String(width)}.png`);
}

/** An approved capture's absolute path -- 1280px only, one file per screen per theme (12 total),
 *  committed to git once a gate (G1/G2/G3) is explicitly approved (D-15). */
export function approvedPngPath(screen: Screen, theme: Theme): string {
  return path.join(APPROVED_ROOT, `${screen}-${theme}.png`);
}

// --- Public site review matrix (10-04-PLAN.md Task 1, SITE-03) ---
//
// The public site (`apps/site`, static export) gets its own review tree under
// `docs/ui/review/site/` -- a sibling of the app's own `docs/ui/review/`, never mixed into it,
// so a site capture round and an app capture round never collide or overwrite each other.

/** The directory every site-review-round capture is written under. */
export const SITE_REVIEW_ROOT = path.join(REVIEW_ROOT, 'site');

/** The six surfaces `capture-site-review.ts` visits, in order: the landing page, four
 *  representative docs pages (one per sidebar group, D-08), and the 404 page. */
export const SITE_PAGES = [
  { id: 'landing', path: '/' },
  { id: 'docs-install', path: '/docs/getting-started/install' },
  { id: 'docs-first-server', path: '/docs/getting-started/first-server' },
  { id: 'docs-concept-server', path: '/docs/concepts/server' },
  { id: 'docs-scope', path: '/docs/reference/scope' },
  { id: 'not-found', path: '/this-page-does-not-exist' },
] as const;

/** A `SITE_PAGES` id, plus the one extra surface that has no page of its own: the landing
 *  captured a second time with `prefers-reduced-motion` instead of a fresh route (D-18). */
export type SiteSurface = (typeof SITE_PAGES)[number]['id'] | 'landing-reduced-motion';

/** A site-review-round capture's absolute path -- one file per surface, theme and width. */
export function siteReviewPngPath(surface: SiteSurface, theme: Theme, width: Width): string {
  return path.join(SITE_REVIEW_ROOT, `${surface}-${theme}-${String(width)}.png`);
}
